PUT http://localhost:3001/api/persons/61cf57b0b1e7d6c651877a03
Content-Type: application/json

{
  "name": "Benji Bad",
  "number": "123456789"
}

### 
POST https://intense-headland-44740.herokuapp.com/api/persons/
Content-Type: application/json

{
  "name": "Dan Abramov",
  "number": "123-456-7890"
}

###
POST https://intense-headland-44740.herokuapp.com/api/persons/
Content-Type: application/json

{
  "number": "123-456-7890"
}

###
POST https://intense-headland-44740.herokuapp.com/api/persons/
Content-Type: application/json

{
  "name": "Test2"
}
